### ISSUE TITLE
view_left and view_right the same?

### ISSUE THREAD

**Issue by tiye** [aslpavel/fingertree-rs#1]
I guessing they are copied:

https://github.com/aslpavel/fingertree-rs/commit/497ca0589cf168b11b6506e5108c698b4aaca8f7#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R174-R198

are they different? or really identical?

originally found on https://docs.rs/fingertrees/0.2.4/fingertrees/struct.FingerTree.html#method.view_left .

**Comment by aslpavel** [comment]
Hi! I'm not sure I understand the question, but if I do one of them call `self.rec.view_left` and the other calls `self.rec.view_right` which are passed to `Tree::left_view` and `Tree::right_view` respectively

**Comment by tiye** [comment]
"right side" for `view_right`?

![image](https://user-images.githubusercontent.com/449224/139779721-c022b1cc-bcde-4d0c-9ea1-411d86d1cb49.png)

**Comment by aslpavel** [comment]
I see, thank you! I will fix it :)
