### ISSUE TITLE
how to understand: overflow evaluating the requirement `Size<Calcit>: Measured`

### ISSUE THREAD

**Issue by tiye** [aslpavel/fingertree-rs#5]
I could bypass the error by adding extra `Arc`s to break recursions in my own data types. But that comes with costs.

https://github.com/calcit-lang/calcit_runner.rs/blob/main/src/primes.rs#L73-L74

How is exactly the error happened?

```
error[E0275]: overflow evaluating the requirement `Size<Calcit>: Measured`
   --> src/data/cirru.rs:9:67
    |
9   | pub fn code_to_calcit(xs: &Cirru, ns: Arc<str>, def: Arc<str>) -> Result<Calcit, String> {
    |                                                                   ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: required because of the requirements on the impl of `Refs<Size<Calcit>>` for `ArcRefs`
note: required because it appears within the type `Calcit`
   --> src/primes.rs:54:10
    |
54  | pub enum Calcit {
    |          ^^^^^^
note: required by a bound in `Result`
   --> /Users/chen/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:503:17
    |
503 | pub enum Result<T, E> {
    |                 ^ required by this bound in `Result`
```

```
error[E0275]: overflow evaluating the requirement `Size<Calcit>: Measured`
  --> src/builtins/effects.rs:40:22
   |
40 | pub fn cpu_time(_xs: &CalcitItems) -> Result<Calcit, CalcitErr> {
   |                      ^^^^^^^^^^^^
   |
   = note: required because of the requirements on the impl of `Refs<Size<Calcit>>` for `ArcRefs`
note: required because it appears within the type `Calcit`
  --> src/primes.rs:54:10
   |
54 | pub enum Calcit {
   |          ^^^^^^
note: required by a bound in `FingerList`
  --> src/primes/finger_list.rs:19:23
   |
19 | pub struct FingerList<T>(FingerTree<ArcRefs, Size<T>>)
   |                       ^ required by this bound in `FingerList`
```

...and many more.

**Comment by aslpavel** [comment]
Why do you have this https://github.com/calcit-lang/calcit_runner.rs/blob/main/src/primes/finger_list.rs#L103-L112 ?

**Comment by tiye** [comment]
was trying that before added on `Calcit` itself. this piece totally unnecessary?

tried to remove the code, still have errors.

**Comment by aslpavel** [comment]
I do not think you need to make anything `Measured` since when you put things in it is already wrapped in the `Size` struct which implements `Measured` and it does not require type inside to be `Measured`. Idea behind measured type is very simple we need to be able to get `Monoid` value associated with the item inside of finger tree, `Size` wrapper just associates constant `1` with any item, and when you to join two monoids it will just sum it, this way you can track the size of the structure.

**Comment by tiye** [comment]
Agreed. I was wrong at first try. However the errors remain after I removed these 2 implementation of `Measured`.

My guess is recursion in my data type got involved into some problem...but I couldn't figure that out.

**Comment by tiye** [comment]
reduced code to:

```rust
pub use fingertrees::measure::Size;
use fingertrees::{ArcRefs, FingerTree};
use std::fmt::Debug;

fn main() {
  let a: C = C::Nil;
}

#[derive(Debug, Clone)]
pub enum C {
  Nil,
  Bool(bool),
  /// not for data, but for recursion
  Recur(FingerTree<ArcRefs, Size<C>>),
  List(FingerTree<ArcRefs, Size<C>>),
}
```

got errors:

```
   Compiling recur-tree v0.1.0 (/Users/chen/repo/gist/recur-tree)
error[E0275]: overflow evaluating the requirement `Size<C>: Measured`
  --> src/main.rs:14:9
   |
14 |   Recur(FingerTree<ArcRefs, Size<C>>),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: required because of the requirements on the impl of `Refs<Size<C>>` for `ArcRefs`
   = note: required because it appears within the type `FingerTree<ArcRefs, Size<C>>`
   = note: no field of an enum variant may have a dynamically sized type
   = help: change the field's type to have a statically known size
help: borrowed types always have a statically known size
   |
14 |   Recur(&FingerTree<ArcRefs, Size<C>>),
   |         +
help: the `Box` type always has a statically known size and allocates its contents in the heap
   |
14 |   Recur(Box<FingerTree<ArcRefs, Size<C>>>),
   |         ++++                            +

error[E0275]: overflow evaluating the requirement `Size<C>: Measured`
   --> src/main.rs:9:17
    |
9   | #[derive(Debug, Clone)]
    |                 ^^^^^
    |
    = note: required because of the requirements on the impl of `Refs<Size<C>>` for `ArcRefs`
note: required because it appears within the type `C`
   --> src/main.rs:10:10
    |
10  | pub enum C {
    |          ^
note: required by a bound in `Clone`
   --> /Users/chen/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/clone.rs:108:18
    |
108 | pub trait Clone: Sized {
    |                  ^^^^^ required by this bound in `Clone`
    = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0275`.
error: could not compile `recur-tree` due to 2 previous errors
```


okay at least it's already telling me to use Box(not sure if it could be faster or not). But not worked out the other problem.

**Comment by aslpavel** [comment]
Yes this error is super confusing, I think issue is misreported here, main problem here is that finger tree is not allocating anything on the heap if it only contain one element. Resulting structure for single element would look like this:
```rust
struct _C_ {
  Recur( FingerTree {
    rec: Tree::Single(Node { inner: NodeInner::Leaf(  _C_::Recur(...) ) })
  })
}
```
As you can see you will end up with infinite sized type.

**Comment by tiye** [comment]
So it's not a bug since the existence of `Single > Node` hierarchy, while the other branches uses Arc/Rc refs.

How about using an extra Ref for Single? It seems it could be more consistent with other branches with all nested children wrapped inside Refs. Or would that slow down the performance?

**Comment by aslpavel** [comment]
I could, but I think it will make it slower, since all the other nodes contain at least 2 leafs it would increase number of allocations by a factor of ~2. I think it would be easier for your to wrap whole finger tree into a  in a reference counter type, or do something similar to `Node` type in this crate for your calcit type and introduce inner type and calcit type which wraps calcitinner into a reference counted pointer.

**Comment by tiye** [comment]
can't disagree.. anyway we have some penalty in performance.
